//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFirstService")]
public interface IFirstService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetData", ReplyAction="http://tempuri.org/IFirstService/GetDataResponse")]
    string GetData(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstService/GetData", ReplyAction="http://tempuri.org/IFirstService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFirstServiceChannel : IFirstService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FirstServiceClient : System.ServiceModel.ClientBase<IFirstService>, IFirstService
{
    
    public FirstServiceClient()
    {
    }
    
    public FirstServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(string name)
    {
        return base.Channel.GetData(name);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(string name)
    {
        return base.Channel.GetDataAsync(name);
    }
}
