//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.SalesVolumeOperation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesVolumeOperation.ISalesVolumeOperation")]
    public interface ISalesVolumeOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesVolumeOperation/ShowSalesVolume", ReplyAction="http://tempuri.org/ISalesVolumeOperation/ShowSalesVolumeResponse")]
        string ShowSalesVolume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesVolumeOperation/ShowSalesVolume", ReplyAction="http://tempuri.org/ISalesVolumeOperation/ShowSalesVolumeResponse")]
        System.Threading.Tasks.Task<string> ShowSalesVolumeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesVolumeOperationChannel : WebApplication1.SalesVolumeOperation.ISalesVolumeOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesVolumeOperationClient : System.ServiceModel.ClientBase<WebApplication1.SalesVolumeOperation.ISalesVolumeOperation>, WebApplication1.SalesVolumeOperation.ISalesVolumeOperation {
        
        public SalesVolumeOperationClient() {
        }
        
        public SalesVolumeOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesVolumeOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesVolumeOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesVolumeOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ShowSalesVolume() {
            return base.Channel.ShowSalesVolume();
        }
        
        public System.Threading.Tasks.Task<string> ShowSalesVolumeAsync() {
            return base.Channel.ShowSalesVolumeAsync();
        }
    }
}
